name: Build, Test and Deploy LI\ibrary App

on:
  push:
    branches: [ "main" ]
  pull_request:
    branches: [ "main" ]
  workflow_dispatch:

jobs:
  deploy_be:
    runs-on: ubuntu-latest
    if: github.ref == 'refs/heads/main'

    steps:
      - name: Deploy BE to production
        uses: JorgeLNJunior/render-deploy@v1.4.5
        with:
            service_id: ${{secrets.MY_RENDER_SERVICE_BE_ID }}
            api_key: ${{ secrets.MY_RENDER_API_KEY }}
            wait_deploy: true

  deploy_fe:
    runs-on: ubuntu-latest
    needs: deploy_be
    if: github.ref == 'refs/heads/main'

    steps:
      - name: Deploy FE to production
        uses: JorgeLNJunior/render-deploy@v1.4.5
        with:
            service_id: ${{secrets.MY_RENDER_SERVICE_FE_ID }}
            api_key: ${{ secrets.MY_RENDER_API_KEY }}
            wait_deploy: true
