name: Build, Test and Deploy LI\ibrary App

on:
  push:
    branches: [ "main" ]
  pull_request:
    branches: [ "main" ]
  workflow_dispatch:

jobs:
  build_test:

    runs-on: ubuntu-latest

    steps:
    - name: Checkout the repository
      uses: actions/checkout@v4
    - name: Use Node.js 20
      uses: actions/setup-node@v4
      with:
        node-version: 20
    - name: Install dependencies
      run: npm install
    - name: Install Playwright browsers
      run: npx playwright install
    - name: Start the Backend
      run: npm run server &
    - name: Start the Frontend
      run: npm run start &
    - name: Run integration tests
      run: npm run test

  deploy_be:
    runs-on: ubuntu-latest
    needs: build_test
    if: github.ref == 'refs/heads/main'

    steps:
      - name: Deploy to production
        uses: JorgeLNJunior/render-deploy@v1.4.5
        with:
            service_id: ${{secrets.MY_RENDER_SERVICE_BE_ID }}
            api_key: ${{ secrets.MY_RENDER_API_KEY }}
            wait_deploy: true
